### PR TITLE
Added Authentication

### PR DESCRIPTION
**Pull request by anthonytang**
I added authentication functionalities to the website. I made a new database in Vercel using Postgres and Prisma for user info. This database will keep track of usernames, emails, and passwords. I also made some basic register and login pages. I also added a master password functionality that should allow us to access any account if needed. 
Register Page:
Screenshot 2024-01-09 at 1 30 16 PM
Login Page:
Screenshot 2024-01-09 at 1 32 24 PM

### CODE REVIEW

**Comment by kongeNikhilKumar** [comment]
@anthonytang  please remove the .env file, No env details should be exposed in a GitHub repository.

**Comment by anthonytang** [comment]
> @anthonytang please remove the .env file, No env details should be exposed in a GitHub repository.

I added it to the gitignore file. Is it hidden now?

**Comment by Versayce** [comment]
It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.

**Comment by anthonytang** [comment]
> It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.

I can update the Layout.js file to the newest one, but that will get rid of the logout functionality. Is that fine? Also, it does appear that a few lines were accidentally changed in the test/components/LoginForm/Login.js file so I will update that back to normal.

**Comment by Versayce** [comment]
> > It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.
> 
> I can update the Layout.js file to the newest one, but that will get rid of the logout functionality. Is that fine? Also, it does appear that a few lines were accidentally changed in the test/components/LoginForm/Login.js file so I will update that back to normal.

You're not able to merge main updates into your branch and keep the code you wrote? I figured you should be able to rebase it. I didn't realize next had built in auth functionality, so I'm not too familiar with it. Is it necessary for the top level layout.js file to be async rather than create a helper function or wrapper for our pages requiring auth? I was thinking that I could transfer the session checking logic to redux, but am still trying to completely grasp how to properly user server and client components to effectively utilize server side rendering. If auth works better apart from redux then I'm fine with keeping it how it is, I might play with it later just so I can understand everything.

**Comment by anthonytang** [comment]
> > > It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.
> > 
> > 
> > I can update the Layout.js file to the newest one, but that will get rid of the logout functionality. Is that fine? Also, it does appear that a few lines were accidentally changed in the test/components/LoginForm/Login.js file so I will update that back to normal.
> 
> You're not able to merge main updates into your branch and keep the code you wrote? I figured you should be able to rebase it. I didn't realize next had built in auth functionality, so I'm not too familiar with it. Is it necessary for the top level layout.js file to be async rather than create a helper function or wrapper for our pages requiring auth? I was thinking that I could transfer the session checking logic to redux, but am still trying to completely grasp how to properly user server and client components to effectively utilize server side rendering. If auth works better apart from redux then I'm fine with keeping it how it is, I might play with it later just so I can understand everything.

I can merge it back. For the layout.js file, I think it depends on whether we want to use server-side authentication or client-side authentication. NextAuth does have session checking capabilities but we can also use Redux if you're more comfortable with that.

**Comment by Versayce** [comment]
> > > > It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.
> > > 
> > > 
> > > I can update the Layout.js file to the newest one, but that will get rid of the logout functionality. Is that fine? Also, it does appear that a few lines were accidentally changed in the test/components/LoginForm/Login.js file so I will update that back to normal.
> > 
> > 
> > You're not able to merge main updates into your branch and keep the code you wrote? I figured you should be able to rebase it. I didn't realize next had built in auth functionality, so I'm not too familiar with it. Is it necessary for the top level layout.js file to be async rather than create a helper function or wrapper for our pages requiring auth? I was thinking that I could transfer the session checking logic to redux, but am still trying to completely grasp how to properly user server and client components to effectively utilize server side rendering. If auth works better apart from redux then I'm fine with keeping it how it is, I might play with it later just so I can understand everything.
> 
> I can merge it back. For the layout.js file, I think it depends on whether we want to use server-side authentication or client-side authentication. NextAuth does have session checking capabilities but we can also use Redux if you're more comfortable with that.

Ok, I'm cool with going with next.js auth

**Comment by anthonytang** [comment]
> > > > > It looks like the .env is hidden now. There's a bit of old code being pushed back into the repo in the Layout.js and Login.js test file. Could you make sure to pull anything that might be missing and get your local version updated with the more recent pushes made and redo the pr? I also think you might be doing more than you need to frontend wise, but I need to look this over some more because I might have some questions related to working with next properly as I'm new to it.
> > > > 
> > > > 
> > > > I can update the Layout.js file to the newest one, but that will get rid of the logout functionality. Is that fine? Also, it does appear that a few lines were accidentally changed in the test/components/LoginForm/Login.js file so I will update that back to normal.
> > > 
> > > 
> > > You're not able to merge main updates into your branch and keep the code you wrote? I figured you should be able to rebase it. I didn't realize next had built in auth functionality, so I'm not too familiar with it. Is it necessary for the top level layout.js file to be async rather than create a helper function or wrapper for our pages requiring auth? I was thinking that I could transfer the session checking logic to redux, but am still trying to completely grasp how to properly user server and client components to effectively utilize server side rendering. If auth works better apart from redux then I'm fine with keeping it how it is, I might play with it later just so I can understand everything.
> > 
> > 
> > I can merge it back. For the layout.js file, I think it depends on whether we want to use server-side authentication or client-side authentication. NextAuth does have session checking capabilities but we can also use Redux if you're more comfortable with that.
> 
> Ok, I'm cool with going with next.js auth

Ok, sounds good.

**Pull request closed without merging**
